# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm_controller
    - right_arm_controller
    - left_hand_controller
    - right_hand_controller
    - lab_bot_controller

  left_arm_controller:
    type: FollowJointTrajectory
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7
    action_ns: follow_joint_trajectory
    default: False
  right_arm_controller:
    type: FollowJointTrajectory
    joints:
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
      - right_joint7
    action_ns: follow_joint_trajectory
    default: False
  left_hand_controller:
    type: FollowJointTrajectory
    joints:
      - left_finger_width_joint
    action_ns: follow_joint_trajectory
    default: True
  right_hand_controller:
    type: FollowJointTrajectory
    joints:
      - right_finger_width_joint
    action_ns: follow_joint_trajectory
    default: True
  lab_bot_controller:
    type: FollowJointTrajectory
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7
      - left_finger_width_joint
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
      - right_joint7
      - right_finger_width_joint
    action_ns: follow_joint_trajectory
    default: true