# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    lab_bot_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm_controller:
  ros__parameters:
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_arm_controller:
  ros__parameters:
    joints:
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
      - right_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
left_hand_controller:
  ros__parameters:
    joints:
      - left_finger_width_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_hand_controller:
  ros__parameters:
    joints:
      - right_finger_width_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
lab_bot_controller:
  ros__parameters:
    joints:
      - left_joint1
      - left_joint2
      - left_joint3
      - left_joint4
      - left_joint5
      - left_joint6
      - left_joint7
      - left_finger_width_joint
      - right_joint1
      - right_joint2
      - right_joint3
      - right_joint4
      - right_joint5
      - right_joint6
      - right_joint7
      - right_finger_width_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity